(use-modules (ice-9 threads))
(use-modules (statprof))

(import (srfi srfi-1) (ice-9 match) (srfi srfi-8) (srfi srfi-9))
(import (ffi cblas))
(load "common-lisp.scm")
(load "common.scm")
(load "mat.scm")
(load "net.scm")
(load "rl.scm")
(load "backgammon.scm")
(load "td-gammon.scm")

(define (main)
  (init-rand)
  (let* ((wnet (make-net))
         (bnet (make-net))
         (measure #f)
         (episodes #f)
         (start-episode #f)
         (verbose #f)
         ; ---- debug stuff ----
         (threads 1)
         (num-threads (length (all-threads))) ; KLUDGY
         (profiling #f))
    (do ((args (command-line) (cdr args)))
        ((eq? args '()))
      (format #t "  arg: ~s~%" (car args))
      (if (string=? (car args) "--human")
          (set! wnet #:human))
      (if (string-contains (car args) "--random")
          (set! wnet #:random))
      (if (string-contains (car args) "--late")
          (set! wnet #:late))
      (if (string-contains (car args) "--early")
          (set! wnet #:early))
      (if (string-contains (car args) "--bar")
          (set! wnet #:bar))
      (if (string-contains (car args) "--safe")
          (set! wnet #:safe))
      (if (string-contains (car args) "--swap")
          (let ((tmp wnet))
            (set! wnet bnet)
            (set! bnet tmp)))
      (if (string-contains (car args) "--wnet=")
          (set! wnet (file-load-net (substring (car args) 7) #t)))
      (if (string-contains (car args) "--bnet=")
          (set! bnet (file-load-net (substring (car args) 7) #f)))
      (if (string-contains (car args) "--measure=")
          (set! measure (substring (car args) 10)))
      (if (string-contains (car args) "--episodes=")
          (set! episodes (string->number (substring (car args) 11))))
      (if (string-contains (car args) "--start-episode=")
          (set! start-episode (string->number (substring (car args) 16))))
      (if (string-contains (car args) "--verbose")
          (set! *verbose* #t))
      (if (string-contains (car args) "--profiling")
          (set! profiling #t))
      (if (string-contains (car args) "--threads=")
          (set! threads (string->number (substring (car args) 10)))))

    (do ((i 0 (+ i 1)))
        ((>= i threads))
      (let ((thunk (lambda ()
                     (format #t "Starting thread ~a/~a~%" i threads)
                     (cond
                      (measure
                       (run-tdgammon-measure measure #:episodes episodes #:thread i))
                      (else
                       (run-tdgammon wnet bnet #:save #t #:episodes episodes #:start-episode start-episode #:verbose verbose #:thread i))))))
        (if (= threads 1)
            ; only do profiling if one threads is used
            (if profiling
                (statprof thunk)
                (thunk))
            (call-with-new-thread thunk))))
    (if (> threads 1)
        (begin
          (format #t "All threads are started ~a~%" threads)
          (do ()
              ((= (length (all-threads)) num-threads))
            (format #t "current threads: ~a~%" (length (all-threads)))
            (sleep 10))))))

(main)
